In [1]:
import numpy as np
import math
import random

In [17]:
class PBIL(object):
    def __init__(self,n=5,m=5):
        self.PV=np.full((1,m),0.5)
        self.n=n
        self.m=m
        self.imgMAT = np.random.uniform(low=0.0, high=255.0,size=(n,m)) #Should be given
        self.pop = np.random.choice(2,self.n*self.m,self.PV.tolist()).reshape(self.n,self.m)
        self.TimgMAT = np.random.uniform(low=0, high=0,size=(n,m)) #given imgMAT to be TRUNC 
        self.fitness=np.zeros(self.m)
        self.best_chromosome_index=-1
        self.best_chromosome_list=np.array
        self.LR=0.2
        self.MS=0.05
        
    def printData(self):
        print('Probability_vector=\n',self.PV)
        print('Population=\n',self.pop)
        print('Image =\n',self.imgMAT)
        print('Translated/Truncated Image =\n',self.TimgMAT)
    
    def original_Image_Matrix(self):#embedded watermark
        for i in range(self.n):
            for j in range(self.m):
                self.imgMAT[i][j]=round(self.imgMAT[i][j])
    
    def translateImg(self):
        for i in range(self.n):
            for j in range(self.m):
                if self.pop[i][j]==1:
                    self.TimgMAT[i][j] = math.trunc(self.imgMAT[i][j])+1
                else:
                    self.TimgMAT[i][j] = math.trunc(self.imgMAT[i][j])
    
    def calculate_fitness(self):
        self.fitness=np.zeros(self.m)
        self.original_Image_Matrix()
        for i in range(self.n):
            for j in range(self.m):
                self.fitness[i]+=int(abs(self.TimgMAT[i][j]-round(self.imgMAT[i][j])))
        self.best_chromosome_index=np.where(self.fitness == np.amin(self.fitness))
        self.best_chromosome_list=[i for i in self.pop[self.best_chromosome_index[0]].tolist()]
#         print('Best Chromosomes possible',self.best_chromosome_list)
    
    def update_PV(self):
        Solution_Vector = self.best_chromosome_list[0] 
        for i in range(len(self.PV)):
            self.PV[i]=self.PV[i]*(1-self.LR)+Solution_Vector[i]*self.LR
#         print('updated PV',self.PV)
        
    def mutate_PV(self):
        for i in range(len(self.PV)):
            self.PV[i]=self.PV[i]*(1-self.MS)+random.randint(0, 1)*self.LR
#         print('mutated PV',self.PV)
    
    def Generate(self):
        while(True):
            self.pop=np.random.choice(2,self.n*self.m,self.PV.tolist()).reshape(self.n,self.m)
            self.translateImg()
            self.calculate_fitness()
            self.update_PV()
            self.mutate_PV()
            BC=self.best_chromosome_list
            # print(self.fitness)
            if len(BC)==self.n and np.amin(self.fitness)<=1:
                break
        self.printData()
        
        
a = PBIL()
a.Generate()

Streaming output truncated to the last 5000 lines.
[1. 1. 3. 3. 4.]
[3. 3. 3. 2. 2.]
[2. 4. 2. 3. 4.]
[3. 4. 2. 1. 2.]
[1. 4. 3. 3. 3.]
[2. 2. 4. 2. 2.]
[2. 2. 2. 2. 1.]
[4. 3. 4. 3. 0.]
[2. 2. 4. 3. 1.]
[4. 2. 3. 3. 3.]
[4. 1. 2. 2. 3.]
[4. 1. 2. 3. 1.]
[4. 3. 4. 4. 1.]
[1. 4. 2. 1. 3.]
[2. 4. 2. 3. 3.]
[3. 1. 3. 2. 1.]
[1. 3. 2. 3. 3.]
[1. 2. 0. 2. 2.]
[4. 3. 2. 2. 4.]
[3. 1. 4. 2. 3.]
[3. 3. 4. 4. 3.]
[2. 3. 2. 4. 1.]
[3. 2. 1. 4. 5.]
[2. 2. 2. 2. 1.]
[2. 2. 4. 3. 1.]
[3. 3. 1. 2. 1.]
[1. 3. 3. 4. 3.]
[2. 2. 2. 3. 2.]
[1. 3. 3. 4. 1.]
[2. 2. 2. 2. 1.]
[2. 4. 1. 2. 2.]
[3. 3. 3. 3. 5.]
[2. 1. 4. 3. 2.]
[5. 2. 4. 1. 3.]
[2. 3. 2. 3. 2.]
[3. 0. 1. 3. 4.]
[1. 4. 0. 4. 2.]
[3. 4. 2. 2. 3.]
[2. 4. 4. 1. 2.]
[4. 1. 3. 2. 2.]
[2. 5. 2. 2. 3.]
[3. 3. 2. 4. 1.]
[3. 3. 2. 4. 3.]
[2. 3. 2. 4. 1.]
[2. 3. 2. 2. 1.]
[4. 2. 4. 3. 4.]
[2. 2. 5. 3. 2.]
[1. 1. 1. 2. 3.]
[1. 4. 3. 2. 3.]
[5. 2. 4. 3. 4.]
[1. 2. 1. 2. 4.]
[3. 0. 3. 4. 1.]
[1. 3. 5. 3. 4.]
[2. 3. 2. 3. 3.]
[4. 3. 3. 3. 2.]
[2. 2. 2. 3. 4